services:
  app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    container_name: vistalab_app
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vistalab_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_USER: ${DOCKER_DB_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
