version: '3.8'
services:
  app:
    build: .
    image: vistalab-client:latest
    restart: unless-stopped
    env_file: .env
    environment:
      SERVER_NAME: ":8080"
      FRANKENPHP_CONFIG: "worker ./public/index.php"
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
