services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: vistalab_app
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    container_name: vistalab_nginx
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: vistalab_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: vistalab_redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: vistalab_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data:
